import { join } from "node:path";
import type { ModelInfo } from "../types.js";
import { MODEL_DIR } from "../constants.js";

export const CURATED_MODELS: ModelInfo[] = [
  {
    name: "Ministral 3B Instruct (Q8_0)",
    description: "Requires ~3.4 GB memory. Mistral's 3B instruct model. Default.",
    isDefault: true,
    hfUri: join(MODEL_DIR, "Ministral-3-3B-Instruct-2512-Q8_0.gguf"),
    contextSize: 4096,
    sizeLabel: "~3.4 GB",
    inferenceParams: {
      temperature: 0.4,
      topP: 0.9,
      topK: 40,
      minP: 0.05,
      repeatPenalty: {
        lastTokens: 64,
        penalty: 1.1,
        frequencyPenalty: 0.05,
        presencePenalty: 0.05,
        penalizeNewLine: false,
      },
    },
  },
  {
    name: "Qwen 3 4B Instruct (Q4_K_M)",
    description: "Requires ~2.5 GB memory. Strong instruction following. Matches Qwen 2.5 7B quality.",
    hfUri: join(MODEL_DIR, "Qwen3-4B-Q4_K_M.gguf"),
    contextSize: 4096,
    sizeLabel: "~2.5 GB",
    inferenceParams: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0.0,
      repeatPenalty: {
        lastTokens: 64,
        penalty: 1.1,
        frequencyPenalty: 0.0,
        presencePenalty: 0.5,
        penalizeNewLine: false,
      },
    },
  },
  {
    name: "Llama 3.1 8B Instruct (IQ3_M)",
    description: "Requires ~3.7 GB memory. Proven general-purpose 8B instruct model.",
    hfUri: join(MODEL_DIR, "Meta-Llama-3.1-8B-Instruct-IQ3_M.gguf"),
    contextSize: 4096,
    sizeLabel: "~3.7 GB",
    inferenceParams: {
      temperature: 0.6,
      topP: 0.9,
      topK: 40,
      minP: 0.05,
      repeatPenalty: {
        lastTokens: 64,
        penalty: 1.15,
        frequencyPenalty: 0.1,
        presencePenalty: 0.1,
        penalizeNewLine: false,
      },
    },
  },
  {
    name: "Mistral 7B Instruct v0.3 (Q3_K_L)",
    description: "Requires ~3.6 GB memory. Proven instruction follower.",
    hfUri: join(MODEL_DIR, "Mistral-7B-Instruct-v0.3.Q3_K_L.gguf"),
    contextSize: 4096,
    sizeLabel: "~3.6 GB",
    inferenceParams: {
      temperature: 0.4,
      topP: 0.9,
      topK: 40,
      minP: 0.05,
      repeatPenalty: {
        lastTokens: 64,
        penalty: 1.1,
        frequencyPenalty: 0.05,
        presencePenalty: 0.05,
        penalizeNewLine: false,
      },
    },
  },
  {
    name: "WizardLM-2 7B (Q3_K_L)",
    description: "Requires ~3.6 GB memory. Tuned for complex instruction following.",
    hfUri: join(MODEL_DIR, "WizardLM-2-7B.Q3_K_L.gguf"),
    contextSize: 4096,
    sizeLabel: "~3.6 GB",
    inferenceParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 40,
      minP: 0.05,
      repeatPenalty: {
        lastTokens: 64,
        penalty: 1.1,
        frequencyPenalty: 0.05,
        presencePenalty: 0.05,
        penalizeNewLine: false,
      },
    },
  },
  {
    name: "Jan v3 4B Instruct (Q6_K)",
    description: "Requires ~3.0 GB memory. Compact 4B instruct model.",
    hfUri: join(MODEL_DIR, "Jan-v3-4b-base-instruct-Q6_K.gguf"),
    contextSize: 4096,
    sizeLabel: "~3.0 GB",
    inferenceParams: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0.05,
      repeatPenalty: {
        lastTokens: 64,
        penalty: 1.1,
        frequencyPenalty: 0.0,
        presencePenalty: 0.0,
        penalizeNewLine: false,
      },
    },
  },
];
